name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Adjust based on your project's language
        python-version: [3.11, 3.12]
        # node-version: [18, 20]
        # go-version: [1.21, 1.22]
    
    steps:
    - uses: actions/checkout@v4
    
    # Python setup (uncomment if using Python)
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    
    - name: Install dependencies
      run: |
        if [ -f pyproject.toml ]; then
          uv sync --dev
        elif [ -f requirements.txt ]; then
          uv pip install -r requirements.txt
        fi
    
    # Node.js setup (uncomment if using Node.js)
    # - name: Set up Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # 
    # - name: Install Node dependencies
    #   run: npm ci
    
    # Go setup (uncomment if using Go)
    # - name: Set up Go ${{ matrix.go-version }}
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: ${{ matrix.go-version }}
    # 
    # - name: Install Go dependencies
    #   run: go mod download
    
    - name: Run linting
      run: make lint
    
    - name: Run type checking
      run: make type-check
    
    - name: Run tests
      run: make test

    - name: Run security scan
      run: make security

    - name: DevSpace config check (advisory)
      if: ${{ !cancelled() && (hashFiles('devspace.yaml','devspace.yml','.devspace/devspace.yaml') != '') }}
      continue-on-error: true
      run: |
        if command -v devspace >/dev/null 2>&1; then
          echo "DevSpace detected; validating configuration (no cluster actions)"
          devspace print config >/dev/null || echo "⚠️ DevSpace config parse failed"
        else
          echo "DevSpace CLI not installed on runner; skipping"
        fi

    - name: SLO synthetic (advisory)
      if: always()
      continue-on-error: true
      run: |
        if [[ -x ".gobuildme/scripts/bash/slo-synthetic.sh" ]]; then
          .gobuildme/scripts/bash/slo-synthetic.sh || true
        else
          echo "No SLO synthetic script found; skipping"
        fi

    - name: Upload SLO report artifact
      if: always() && hashFiles('.gobuildme/self-driving/logs/slo-report.json') != ''
      uses: actions/upload-artifact@v4
      with:
        name: slo-report
        path: .gobuildme/self-driving/logs/slo-report.json
        if-no-files-found: ignore

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build project
      run: make build
