#!/usr/bin/env pwsh
# Purpose: Generate test fixtures, factories, and mocks
# Why: Provides reusable test data for all test types
# How: Analyzes data models and architecture to generate fixtures

param(
    [switch]$DryRun,
    [switch]$Help
)

# Source common utilities
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

if (-not (Test-Path "$ScriptDir/qa-common.ps1")) {
    Write-Host "Error: qa-common.ps1 not found in $ScriptDir" -ForegroundColor Red
    exit 1
}

. "$ScriptDir/qa-common.ps1"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Parse arguments
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if ($Help) {
    Write-Host "Usage: generate-fixtures.ps1 [OPTIONS]"
    Write-Host ""
    Write-Host "Generate test fixtures, factories, and mocks"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -DryRun    Preview changes without modifying files"
    Write-Host "  -Help      Show this help message"
    exit 0
}

$env:DRY_RUN = if ($DryRun) { "true" } else { "false" }

Write-Host "🏭 Generating test fixtures and mocks..."
if (Test-DryRun) {
    Write-Host "   [DRY-RUN MODE - No files will be modified]"
}
Write-Host ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Create backup before making changes
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if (-not (Test-DryRun)) {
    $backupDir = New-TestBackup "generate-fixtures"
    Write-Info "Backup created: $backupDir"
    Write-Host ""
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Step 1: Check and generate architecture
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Test-AndGenerateArchitecture

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Step 2: Load architecture and feature context
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$archContext = Get-ArchitectureContext
$integrationLandscape = Get-IntegrationLandscape
$featureContext = Get-FeatureContext

$language = if ($archContext -and $archContext.Language) { $archContext.Language } else { Get-ProjectLanguage }
$framework = if ($archContext -and $archContext.Framework) { $archContext.Framework } else { "unknown" }

Write-Section "📊 Context Loaded"
Write-Host "Language:        $language"
Write-Host "Framework:       $framework"
Write-Host "Test Framework:  $(if ($archContext -and $archContext.TestFramework) { $archContext.TestFramework } else { 'auto-detect' })"

if ($featureContext.Entities -and $featureContext.Entities.Count -gt 0) {
    Write-Host ""
    Write-Host "Entities found:"
    foreach ($entity in $featureContext.Entities) {
        Write-Host "  • $entity"
    }
}

if ($integrationLandscape -and $integrationLandscape.ExternalServices -and $integrationLandscape.ExternalServices.Count -gt 0) {
    Write-Host ""
    Write-Host "External services found:"
    foreach ($service in $integrationLandscape.ExternalServices) {
        Write-Host "  • $service"
    }
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Step 3: Generate fixtures based on language
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function New-PythonFixtures {
    param($Entities, $ExternalServices)

    Write-Section "🐍 Generating Python Fixtures"

    New-Item -ItemType Directory -Force -Path "tests/fixtures" | Out-Null

    # Generate conftest.py if it doesn't exist
    if (-not (Test-Path "tests/fixtures/conftest.py")) {
        $conftest = @'
"""
Test fixtures for pytest

This module provides reusable fixtures for all tests.
Generated by /gbm.qa.generate-fixtures
"""

import pytest
from typing import Generator

# Add your fixtures here
'@
        Set-Content -Path "tests/fixtures/conftest.py" -Value $conftest
        Write-Success "Created tests/fixtures/conftest.py"
    }

    # Generate entity fixtures
    if ($Entities -and $Entities.Count -gt 0) {
        $entityFixtures = @'
"""
Entity fixtures

Provides fixtures for domain entities.
"""

import pytest
from faker import Faker

fake = Faker()

'@

        foreach ($entity in $Entities) {
            if ($entity) {
                $entityLower = $entity.ToLower()
                $entityFixtures += @"

@pytest.fixture
def ${entityLower}_data():
    `"""Sample ${entity} data`"""
    return {
        "id": fake.random_int(min=1, max=1000),
        "name": fake.name(),
        "created_at": fake.date_time(),
    }


@pytest.fixture
def ${entityLower}(${entityLower}_data):
    `"""${entity} instance`"""
    # TODO: Replace with actual ${entity} model
    return ${entityLower}_data
"@
            }
        }

        Set-Content -Path "tests/fixtures/entity_fixtures.py" -Value $entityFixtures
        Write-Success "Created tests/fixtures/entity_fixtures.py"
    }

    # Generate mock services
    if ($ExternalServices -and $ExternalServices.Count -gt 0) {
        $mockServices = @'
"""
Mock external services

Provides mocks for external service integrations.
"""

import pytest
from unittest.mock import Mock, MagicMock

'@

        foreach ($service in $ExternalServices) {
            if ($service) {
                $serviceLower = $service.ToLower() -replace ' ', '_'
                $mockServices += @"

@pytest.fixture
def mock_${serviceLower}():
    `"""Mock ${service} service`"""
    mock = Mock()
    mock.call.return_value = {"status": "success"}
    mock.get.return_value = {"data": "sample"}
    return mock
"@
            }
        }

        Set-Content -Path "tests/fixtures/mock_services.py" -Value $mockServices
        Write-Success "Created tests/fixtures/mock_services.py"
    }
}

function New-JavaScriptFixtures {
    param($Entities)

    Write-Section "📦 Generating JavaScript Fixtures"

    New-Item -ItemType Directory -Force -Path "tests/fixtures" | Out-Null

    # Generate fixtures index
    $indexJs = @'
/**
 * Test fixtures for Jest/Vitest
 *
 * Provides reusable test data and mocks.
 * Generated by /gbm.qa.generate-fixtures
 */

const { faker } = require('@faker-js/faker');

'@

    # Generate entity fixtures
    if ($Entities -and $Entities.Count -gt 0) {
        foreach ($entity in $Entities) {
            if ($entity) {
                $entityLower = $entity.ToLower()
                $indexJs += @"

/**
 * Generate ${entity} test data
 */
function create${entity}Data() {
  return {
    id: faker.number.int({ min: 1, max: 1000 }),
    name: faker.person.fullName(),
    createdAt: faker.date.recent(),
  };
}

module.exports.create${entity}Data = create${entity}Data;
"@
            }
        }
    }

    Set-Content -Path "tests/fixtures/index.js" -Value $indexJs
    Write-Success "Created tests/fixtures/index.js"
}

function New-PhpFixtures {
    Write-Section "🐘 Generating PHP Fixtures"

    New-Item -ItemType Directory -Force -Path "tests/Fixtures" | Out-Null

    # Generate base fixture class
    $baseFixture = @'
<?php

namespace Tests\Fixtures;

use Faker\Factory;
use Faker\Generator;

/**
 * Base fixture class
 *
 * Provides common fixture functionality.
 * Generated by /gbm.qa.generate-fixtures
 */
abstract class BaseFixture
{
    protected Generator $faker;

    public function __construct()
    {
        $this->faker = Factory::create();
    }
}
'@

    Set-Content -Path "tests/Fixtures/BaseFixture.php" -Value $baseFixture
    Write-Success "Created tests/Fixtures/BaseFixture.php"
}

function New-JavaFixtures {
    Write-Section "☕ Generating Java Fixtures"

    New-Item -ItemType Directory -Force -Path "src/test/java/fixtures" | Out-Null

    # Generate fixture builder
    $testDataBuilder = @'
package fixtures;

import com.github.javafaker.Faker;

/**
 * Test data builder
 *
 * Provides test data generation utilities.
 * Generated by /gbm.qa.generate-fixtures
 */
public class TestDataBuilder {
    private static final Faker faker = new Faker();

    public static Faker getFaker() {
        return faker;
    }
}
'@

    Set-Content -Path "src/test/java/fixtures/TestDataBuilder.java" -Value $testDataBuilder
    Write-Success "Created src/test/java/fixtures/TestDataBuilder.java"
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Step 4: Generate fixtures based on detected language
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$entities = $featureContext.Entities
$externalServices = if ($integrationLandscape) { $integrationLandscape.ExternalServices } else { @() }

switch -Regex ($language) {
    "python|Python" {
        New-PythonFixtures -Entities $entities -ExternalServices $externalServices
    }
    "javascript|JavaScript|typescript|TypeScript" {
        New-JavaScriptFixtures -Entities $entities
    }
    "php|PHP" {
        New-PhpFixtures
    }
    "java|Java" {
        New-JavaFixtures
    }
    default {
        Write-Warning "Language '$language' not fully supported yet"
        Write-Info "Creating basic fixture structure..."
        New-Item -ItemType Directory -Force -Path "tests/fixtures" | Out-Null
    }
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Step 5: Generate report
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

New-Item -ItemType Directory -Force -Path ".gobuildme/specs/qa-test-scaffolding" | Out-Null

$report = @"
# Test Fixtures Generation Report

**Generated**: $(Get-Date)
**Language**: $language
**Framework**: $framework

## Fixtures Created

"@

if ($entities -and $entities.Count -gt 0) {
    $report += @"

### Entity Fixtures

$(($entities | ForEach-Object { "- $_" }) -join "`n")

"@
}

if ($externalServices -and $externalServices.Count -gt 0) {
    $report += @"

### Mock Services

$(($externalServices | ForEach-Object { "- $_" }) -join "`n")

"@
}

$report += @'

## Next Steps

1. Review generated fixtures
2. Customize fixture data for your domain
3. Add relationships between entities
4. Use fixtures in your tests:
   - Import fixtures in test files
   - Use as function parameters
   - Customize as needed

## Usage Examples

### Python (pytest)
```python
def test_example(user, mock_stripe):
    # user and mock_stripe are auto-injected
    assert user.name is not None
```

### JavaScript (Jest)
```javascript
const { createUserData } = require('./fixtures');

test('example', () => {
  const user = createUserData();
  expect(user.name).toBeDefined();
});
```

'@

Set-Content -Path ".gobuildme/specs/qa-test-scaffolding/fixtures-report.md" -Value $report

Write-Section "✅ Fixture Generation Complete"
Write-Host "📄 Report saved to: .gobuildme/specs/qa-test-scaffolding/fixtures-report.md"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Review generated fixtures in tests/fixtures/"
Write-Host "  2. Customize fixture data for your domain"
Write-Host "  3. Use fixtures in your tests"
Write-Host "  4. Run: /gbm.qa.implement-tests"
Write-Host ""
