#!/usr/bin/env bash
# pm-discover.sh - Create discovery session workspace for PM brainstorming and opportunity scoring
set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(CDPATH="" cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# =============================================================================
# PM Discovery Session Setup
# =============================================================================

main() {
    log_info "Setting up PM discovery session..."

    # Generate session ID (timestamp-based)
    local session_id
    session_id="$(date +%Y%m%d-%H%M%S)"

    # Create discovery workspace directory
    local discovery_dir=".gobuildme/specs/pm-discovery/${session_id}"
    mkdir -p "$discovery_dir"

    log_success "Created discovery workspace: $discovery_dir"

    # Create discovery.md from template
    create_discovery_template "$discovery_dir"

    # Create opportunity-matrix.md
    create_opportunity_matrix "$discovery_dir"

    # Create hypotheses.md for top problems
    create_hypotheses_template "$discovery_dir"

    # Create session metadata
    create_session_metadata "$discovery_dir" "$session_id"

    log_info ""
    log_success "✅ PM Discovery session initialized!"
    log_info ""
    log_info "Session ID: $session_id"
    log_info "Workspace: $discovery_dir"
    log_info ""
    log_info "Files created:"
    log_info "  - discovery.md           (Main discovery document)"
    log_info "  - opportunity-matrix.md  (Scoring matrix)"
    log_info "  - hypotheses.md          (Top 3 hypotheses)"
    log_info "  - session-metadata.json  (Session info)"
    log_info ""
    log_info "Next: Follow the /gbm.pm.discover command to:"
    log_info "  1. Explore 3-5 problems"
    log_info "  2. Score opportunities"
    log_info "  3. Form hypotheses"
    log_info "  4. Choose direction"
}

# =============================================================================
# Template Creation Functions
# =============================================================================

create_discovery_template() {
    local dir="$1"
    local file="$dir/discovery.md"

    cat > "$file" <<'EOF'
# PM Discovery Session

**Session ID:** [Generated by script]
**Date:** [YYYY-MM-DD]
**Product Manager:** [Your name]
**Participants:** [PM + any stakeholders involved]

---

## Session Goals

**Purpose:** Explore problems, brainstorm opportunities, score and prioritize to choose direction.

**Target Outcome:** Choose ONE problem to pursue with confidence.

---

## Problem Space Exploration

List all problems/opportunities you're considering. Target: 3-5 problems minimum.

### Problem 1: [One-sentence description]

**Who Experiences This:**
- Target personas: [Primary users affected]
- Frequency: [How often they encounter it]
- Severity: [Critical / High / Medium / Low]

**Evidence So Far:**
- Source 1: [e.g., "25 support tickets in last month"]
- Source 2: [e.g., "Analytics show 40% drop-off at step X"]
- Source 3: [e.g., "5 sales calls mentioned this"]

**Current State:**
- How users handle this today: [Workarounds, manual processes]
- Why it's painful: [What makes it hard/frustrating]

**Business Impact:**
- Revenue: [Lost sales, churn, reduced expansion]
- Cost: [Support overhead, manual work]
- Strategic: [Competitive disadvantage, market gap]

**Initial Confidence:**
- How well do we understand this problem? [High / Medium / Low]
- Why this confidence level: [Reasoning]

---

### Problem 2: [One-sentence description]

[Same structure as Problem 1]

---

### Problem 3: [One-sentence description]

[Same structure as Problem 1]

---

### Problem 4: [One-sentence description]

[Same structure as Problem 1]

---

### Problem 5: [One-sentence description]

[Same structure as Problem 1]

---

## Opportunity Scoring

See `opportunity-matrix.md` for scoring matrix.

**Scoring Framework:**

1. **Impact (1-5)**: How much does solving this matter?
2. **Effort (1-5)**: How hard to solve?
3. **Confidence (1-5)**: How well do we understand it?
4. **Strategic Fit (1-5)**: Aligns with company strategy?

**Formula:** `Score = (Impact × Strategic Fit) / Effort × Confidence`

---

## Top 3 Hypotheses

See `hypotheses.md` for detailed hypothesis formation.

For the top 3 ranked problems from opportunity matrix:

### Problem [N] Hypothesis

**Hypothesis:**
We believe that **[solution concept]** will result in **[measurable outcome]** for **[target users]**.

**Underlying Assumptions:**
1. [Assumption 1]
2. [Assumption 2]
3. [Assumption 3]

**Risks to Validate:**
1. [Risk 1]
2. [Risk 2]
3. [Risk 3]

---

## Final Decision

**Chosen Problem:** [Problem title from matrix]

**Why This One:**
1. [Reason 1: e.g., "Highest impact × strategic fit score"]
2. [Reason 2: e.g., "Aligns with Q2 OKR on retention"]
3. [Reason 3: e.g., "Engineering capacity available"]
4. [Reason 4: e.g., "Can launch before competitor"]

**Alternatives Considered:**

**Problem [X]:** [Title]
- Why not chosen: [Reason]
- Potential future consideration: [Yes/No, When]

**Problem [Y]:** [Title]
- Why not chosen: [Reason]
- Potential future consideration: [Yes/No, When]

**De-Risking Plan:**
Before committing to full solution, we will:
1. [Validation step 1]
2. [Validation step 2]
3. [Validation step 3]

**Go/No-Go Criteria:**
We will proceed to PRD if:
- ✅ [Criterion 1]
- ✅ [Criterion 2]
- ✅ [Criterion 3]

If criteria not met: Revisit discovery or choose different problem.

---

## Next Steps

1. Run `/gbm.pm.interview` to conduct user interviews
2. Target: Complete [N] interviews in [X] weeks
3. After interviews: Run `/gbm.pm.research` for market/competitive analysis
4. Validation checkpoint: Run `/gbm.pm.validate-problem` before PRD

---

## Session Notes

[Any additional notes, insights, or context from brainstorming session]
EOF

    log_success "Created: discovery.md"
}

create_opportunity_matrix() {
    local dir="$1"
    local file="$dir/opportunity-matrix.md"

    cat > "$file" <<'EOF'
# Opportunity Scoring Matrix

**Session ID:** [Generated by script]
**Date:** [YYYY-MM-DD]

---

## Scoring Framework

### Impact (1-5)
- **5** = Critical business need (revenue/retention/efficiency)
- **4** = High impact on key metrics
- **3** = Meaningful improvement
- **2** = Minor improvement
- **1** = Nice to have

### Effort (1-5)
- **5** = XXL (>6 months, multiple teams)
- **4** = XL (3-6 months, cross-functional)
- **3** = L (1-3 months, one team)
- **2** = M (2-4 weeks)
- **1** = S/XS (<2 weeks)

### Confidence (1-5)
- **5** = Very high (validated with data and users)
- **4** = High (strong evidence)
- **3** = Medium (some evidence)
- **2** = Low (assumptions)
- **1** = Very low (speculation)

### Strategic Fit (1-5)
- **5** = Core to company strategy
- **4** = Strong alignment
- **3** = Moderate alignment
- **2** = Weak alignment
- **1** = Off-strategy

---

## Opportunity Score Formula

```
Score = (Impact × Strategic Fit) / Effort × Confidence
```

**Example:**
- Impact: 5, Strategic: 4, Effort: 3, Confidence: 4
- Score = (5 × 4) / 3 × 4 = 20 / 12 = 1.67

**Note:** Higher scores indicate better opportunities (high impact, low effort, high confidence).

---

## Scoring Matrix

| Problem | Impact | Effort | Confidence | Strategic | Score | Rank |
|---------|--------|--------|------------|-----------|-------|------|
| Problem 1: [title] | [1-5] | [1-5] | [1-5] | [1-5] | [X.XX] | [#] |
| Problem 2: [title] | [1-5] | [1-5] | [1-5] | [1-5] | [X.XX] | [#] |
| Problem 3: [title] | [1-5] | [1-5] | [1-5] | [1-5] | [X.XX] | [#] |
| Problem 4: [title] | [1-5] | [1-5] | [1-5] | [1-5] | [X.XX] | [#] |
| Problem 5: [title] | [1-5] | [1-5] | [1-5] | [1-5] | [X.XX] | [#] |

---

## Scoring Rationale

### Problem 1: [Title]

**Impact: [Score]**
[Why this score - what's the business impact?]

**Effort: [Score]**
[Why this score - what's the implementation complexity?]

**Confidence: [Score]**
[Why this score - how well do we understand the problem?]

**Strategic Fit: [Score]**
[Why this score - how does it align with company strategy?]

**Calculated Score: [X.XX]**

---

### Problem 2: [Title]

[Same structure]

---

### Problem 3: [Title]

[Same structure]

---

### Problem 4: [Title]

[Same structure]

---

### Problem 5: [Title]

[Same structure]

---

## Top 3 Ranked Problems

Based on opportunity scores:

1. **Problem [N]:** [Title] (Score: [X.XX])
2. **Problem [M]:** [Title] (Score: [X.XX])
3. **Problem [P]:** [Title] (Score: [X.XX])

These top 3 will have hypotheses formed in `hypotheses.md`.

---

## Notes

[Any additional context or considerations for scoring]
EOF

    log_success "Created: opportunity-matrix.md"
}

create_hypotheses_template() {
    local dir="$1"
    local file="$dir/hypotheses.md"

    cat > "$file" <<'EOF'
# Hypotheses for Top 3 Problems

**Session ID:** [Generated by script]
**Date:** [YYYY-MM-DD]

---

## Hypothesis 1: Problem [N] - [Problem Title]

**Problem Statement:**
[Clear, one-sentence problem statement from discovery]

**Hypothesis:**
We believe that **[solution concept]** will result in **[measurable outcome]** for **[target users]**.

**Example:** We believe that building a real-time dashboard will result in 30% reduction in "where is my data?" support tickets for account managers.

**Underlying Assumptions:**
1. [Assumption 1: e.g., "Users have 5+ minutes to review dashboard daily"]
2. [Assumption 2: e.g., "Data freshness is the primary complaint, not data accuracy"]
3. [Assumption 3: e.g., "Users can interpret charts without training"]

**Risks to Validate:**
1. [Risk 1: What could make this hypothesis wrong?]
2. [Risk 2: What external factors could interfere?]
3. [Risk 3: What might we be overlooking?]

**Success Looks Like (Measurable):**
- Leading indicator 1: [Early signal, e.g., "50% of users view dashboard weekly"]
- Leading indicator 2: [Usage metric, e.g., "Average session time 3+ minutes"]
- Lagging indicator: [Business outcome, e.g., "Support tickets -30% in 3 months"]

**How We'll Validate:**
- Step 1: [e.g., "10 user interviews to understand current behavior"]
- Step 2: [e.g., "Analytics deep-dive on support ticket content"]
- Step 3: [e.g., "Competitive analysis to see if others solved this"]

---

## Hypothesis 2: Problem [M] - [Problem Title]

**Problem Statement:**
[Clear, one-sentence problem statement from discovery]

**Hypothesis:**
We believe that **[solution concept]** will result in **[measurable outcome]** for **[target users]**.

**Underlying Assumptions:**
1. [Assumption 1]
2. [Assumption 2]
3. [Assumption 3]

**Risks to Validate:**
1. [Risk 1]
2. [Risk 2]
3. [Risk 3]

**Success Looks Like (Measurable):**
- Leading indicator 1: [Early signal]
- Leading indicator 2: [Usage metric]
- Lagging indicator: [Business outcome]

**How We'll Validate:**
- Step 1: [Validation method]
- Step 2: [Validation method]
- Step 3: [Validation method]

---

## Hypothesis 3: Problem [P] - [Problem Title]

**Problem Statement:**
[Clear, one-sentence problem statement from discovery]

**Hypothesis:**
We believe that **[solution concept]** will result in **[measurable outcome]** for **[target users]**.

**Underlying Assumptions:**
1. [Assumption 1]
2. [Assumption 2]
3. [Assumption 3]

**Risks to Validate:**
1. [Risk 1]
2. [Risk 2]
3. [Risk 3]

**Success Looks Like (Measurable):**
- Leading indicator 1: [Early signal]
- Leading indicator 2: [Usage metric]
- Lagging indicator: [Business outcome]

**How We'll Validate:**
- Step 1: [Validation method]
- Step 2: [Validation method]
- Step 3: [Validation method]

---

## Hypothesis Selection

**Chosen Hypothesis:** [Problem N]

**Why This One:**
1. [Reason 1: Highest opportunity score]
2. [Reason 2: Strongest evidence so far]
3. [Reason 3: Best strategic alignment]

**Next Steps:**
1. Run `/gbm.pm.interview` to validate assumptions with 10-15 user interviews
2. Run `/gbm.pm.research` for market and competitive validation
3. Run `/gbm.pm.validate-problem` for final go/no-go decision
EOF

    log_success "Created: hypotheses.md"
}

create_session_metadata() {
    local dir="$1"
    local session_id="$2"
    local file="$dir/session-metadata.json"

    cat > "$file" <<EOF
{
  "session_id": "$session_id",
  "created_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "command": "/gbm.pm.discover",
  "phase": "discovery",
  "status": "in_progress",
  "artifacts": {
    "discovery": "discovery.md",
    "opportunity_matrix": "opportunity-matrix.md",
    "hypotheses": "hypotheses.md"
  },
  "next_steps": [
    "/gbm.pm.interview",
    "/gbm.pm.research",
    "/gbm.pm.validate-problem"
  ]
}
EOF

    log_success "Created: session-metadata.json"
}

# =============================================================================
# Execute
# =============================================================================

main "$@"
